### ISSUE TITLE
提示3无法求解

### ISSUE THREAD

**Issue by ghost** [Penguin134/CS102A22S12#4]
提示3给出了经`RIPEMD-128`算法计算的结果`30557199a7502078b04d8ba665a4e5c5`。
在使用经典算法的条件下直接求解原文的复杂度在2¹²⁸，经优化可以达到2¹²⁷。但这**远超**了当前可以承受的范围。请给出概念证明提示3可解。

**Comment by Penguin134** [comment]
你好，这里本来就没有想让同学们计算得到答案，只是告诉同学们有提供题解。题解应该已在一周前转给各老师了。
